name: Daily Python Script

on:
  schedule:
    - cron: '30 14 * * *'
  workflow_dispatch:

jobs:
  run-scripts:
    runs-on: ubuntu-latest  # You can specify other OS types if needed

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Google Cloud credentials
        run: |
          echo "GOOGLE_CREDENTIALS" | base64 --decode > $HOME/gcloud.json
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
      
      - name: Set GOOGLE_CREDENTIALS environment variable
        run: echo "GOOGLE_CREDENTIALS=$HOME/gcloud.json" >> $GITHUB_ENV

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'  # Specify the Python version

      - name: Cache Python packages
        uses: actions/cache@v4
        with:
            path: ~/.cache/pip
            key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
            restore-keys: |
                ${{ runner.os }}-pip-
 
      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run People Relationships 1 script
        run: |
          python followupboss/01_peoplerelationships.py
      
      - name: Run People Relationships 2 script
        run: |
          python followupboss/02_pr_to_gsheet.py

      - name: Run People 1 script
        run: |
          python followupboss/04_people_to_gsheet.py
      
      - name: Run People 2 script
        run: |
          python followupboss/05_leads_to_gsheet.py

