name: Daily Python Script

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  run-scripts:
    runs-on: ubuntu-latest  # You can specify other OS types if needed

    env:
      FOLLOWUPBOSS_APIKEY: ${{ secrets.FOLLOWUPBOSS_APIKEY }}
      FOLLOWUPBOSS_XSYSTEM: ${{ secrets.FOLLOWUPBOSS_XSYSTEM }}
      FOLLOWUPBOSS_XSYSTEMKEY: ${{ secrets.FOLLOWUPBOSS_XSYSTEMKEY }}
      MONGODB_PASSWORD: ${{ secrets.MONGODB_PASSWORD }}
      GSHEET_ID: ${{ secrets.GSHEET_ID }}
      MONGO_URI: ${{ secrets.MONGO_URI }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Google Cloud credentials
        run: |
          echo "${{ secrets.GOOGLE_CREDENTIALS }}" | base64 --decode > $HOME/gcloud.json
        env:
              GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
      
      - name: Set GOOGLE_CREDENTIALS environment variable
        run: echo "GOOGLE_CREDENTIALS=$HOME/gcloud.json" >> $GITHUB_ENV
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'  # Specify the Python version

      - name: Cache Python packages
        uses: actions/cache@v4
        with:
            path: ~/.cache/pip
            key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
            restore-keys: |
                ${{ runner.os }}-pip-
 
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      
      - name: Add project root to PYTHONPATH
        run: echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV

      - name: Set Git identity
        run: |
          git config --global user.email "lemuelt@cljteam.com"
          git config --global user.name "Lemuel"
# removing csv backups
          # git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/lalala0095/christina #
          
      # - name: Run People Relationships 1 script
      #   run: |
      #     python followupboss/01_peoplerelationships.py
      
      # - name: Run People Relationships 2 script
      #   run: |
      #     python followupboss/02_pr_to_gsheet.py

      # - name: Run People 1 script
      #   run: |
      #     python followupboss/04_people_to_gsheet.py
      
      - name: Run People 2 script
        run: |
          python followupboss/05_leads_to_gsheet.py

